//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("BlueSkyModel", "FK_Music_UserInformation_Id", "UserInformation", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebWorld.Modules.MyMusic.UserInformation), "Music", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebWorld.Modules.MyMusic.Music))]

// Original file name:
// Generation date: 2014/2/20 23:15:13
namespace WebWorld.Modules.MyMusic
{
    
    /// <summary>
    /// There are no comments for BlueSkyEntities in the schema.
    /// </summary>
    public partial class BlueSkyEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new BlueSkyEntities object using the connection string found in the 'BlueSkyEntities' section of the application configuration file.
        /// </summary>
        public BlueSkyEntities() : 
                base("name=BlueSkyEntities", "BlueSkyEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new BlueSkyEntities object.
        /// </summary>
        public BlueSkyEntities(string connectionString) : 
                base(connectionString, "BlueSkyEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new BlueSkyEntities object.
        /// </summary>
        public BlueSkyEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "BlueSkyEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Music in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Music> Music
        {
            get
            {
                if ((this._Music == null))
                {
                    this._Music = base.CreateQuery<Music>("[Music]");
                }
                return this._Music;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Music> _Music;
        /// <summary>
        /// There are no comments for UserInformation in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<UserInformation> UserInformation
        {
            get
            {
                if ((this._UserInformation == null))
                {
                    this._UserInformation = base.CreateQuery<UserInformation>("[UserInformation]");
                }
                return this._UserInformation;
            }
        }
        private global::System.Data.Objects.ObjectQuery<UserInformation> _UserInformation;
        /// <summary>
        /// There are no comments for Music in the schema.
        /// </summary>
        public void AddToMusic(Music music)
        {
            base.AddObject("Music", music);
        }
        /// <summary>
        /// There are no comments for UserInformation in the schema.
        /// </summary>
        public void AddToUserInformation(UserInformation userInformation)
        {
            base.AddObject("UserInformation", userInformation);
        }
    }
    /// <summary>
    /// There are no comments for BlueSkyModel.Music in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="BlueSkyModel", Name="Music")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Music : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Music object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="musicName">Initial value of MusicName.</param>
        /// <param name="musicURL">Initial value of MusicURL.</param>
        /// <param name="musicType">Initial value of MusicType.</param>
        public static Music CreateMusic(int id, string musicName, string musicURL, string musicType)
        {
            Music music = new Music();
            music.Id = id;
            music.MusicName = musicName;
            music.MusicURL = musicURL;
            music.MusicType = musicType;
            return music;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property MusicName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string MusicName
        {
            get
            {
                return this._MusicName;
            }
            set
            {
                this.OnMusicNameChanging(value);
                this.ReportPropertyChanging("MusicName");
                this._MusicName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("MusicName");
                this.OnMusicNameChanged();
            }
        }
        private string _MusicName;
        partial void OnMusicNameChanging(string value);
        partial void OnMusicNameChanged();
        /// <summary>
        /// There are no comments for Property MusicURL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string MusicURL
        {
            get
            {
                return this._MusicURL;
            }
            set
            {
                this.OnMusicURLChanging(value);
                this.ReportPropertyChanging("MusicURL");
                this._MusicURL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("MusicURL");
                this.OnMusicURLChanged();
            }
        }
        private string _MusicURL;
        partial void OnMusicURLChanging(string value);
        partial void OnMusicURLChanged();
        /// <summary>
        /// There are no comments for Property MusicType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string MusicType
        {
            get
            {
                return this._MusicType;
            }
            set
            {
                this.OnMusicTypeChanging(value);
                this.ReportPropertyChanging("MusicType");
                this._MusicType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("MusicType");
                this.OnMusicTypeChanged();
            }
        }
        private string _MusicType;
        partial void OnMusicTypeChanging(string value);
        partial void OnMusicTypeChanged();
        /// <summary>
        /// There are no comments for UserInformation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("BlueSkyModel", "FK_Music_UserInformation_Id", "UserInformation")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public UserInformation UserInformation
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<UserInformation>("BlueSkyModel.FK_Music_UserInformation_Id", "UserInformation").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<UserInformation>("BlueSkyModel.FK_Music_UserInformation_Id", "UserInformation").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for UserInformation in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<UserInformation> UserInformationReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<UserInformation>("BlueSkyModel.FK_Music_UserInformation_Id", "UserInformation");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<UserInformation>("BlueSkyModel.FK_Music_UserInformation_Id", "UserInformation", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for BlueSkyModel.UserInformation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="BlueSkyModel", Name="UserInformation")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class UserInformation : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new UserInformation object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="userName">Initial value of UserName.</param>
        /// <param name="password">Initial value of Password.</param>
        /// <param name="nickname">Initial value of Nickname.</param>
        public static UserInformation CreateUserInformation(int id, string userName, string password, string nickname)
        {
            UserInformation userInformation = new UserInformation();
            userInformation.Id = id;
            userInformation.UserName = userName;
            userInformation.Password = password;
            userInformation.Nickname = nickname;
            return userInformation;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this.ReportPropertyChanging("UserName");
                this._UserName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("UserName");
                this.OnUserNameChanged();
            }
        }
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property Nickname in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname
        {
            get
            {
                return this._Nickname;
            }
            set
            {
                this.OnNicknameChanging(value);
                this.ReportPropertyChanging("Nickname");
                this._Nickname = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Nickname");
                this.OnNicknameChanged();
            }
        }
        private string _Nickname;
        partial void OnNicknameChanging(string value);
        partial void OnNicknameChanged();
        /// <summary>
        /// There are no comments for Property Gender in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Gender
        {
            get
            {
                return this._Gender;
            }
            set
            {
                this.OnGenderChanging(value);
                this.ReportPropertyChanging("Gender");
                this._Gender = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Gender");
                this.OnGenderChanged();
            }
        }
        private global::System.Nullable<int> _Gender;
        partial void OnGenderChanging(global::System.Nullable<int> value);
        partial void OnGenderChanged();
        /// <summary>
        /// There are no comments for Property CardID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CardID
        {
            get
            {
                return this._CardID;
            }
            set
            {
                this.OnCardIDChanging(value);
                this.ReportPropertyChanging("CardID");
                this._CardID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CardID");
                this.OnCardIDChanged();
            }
        }
        private string _CardID;
        partial void OnCardIDChanging(string value);
        partial void OnCardIDChanged();
        /// <summary>
        /// There are no comments for Property Age in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Age
        {
            get
            {
                return this._Age;
            }
            set
            {
                this.OnAgeChanging(value);
                this.ReportPropertyChanging("Age");
                this._Age = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Age");
                this.OnAgeChanged();
            }
        }
        private global::System.Nullable<int> _Age;
        partial void OnAgeChanging(global::System.Nullable<int> value);
        partial void OnAgeChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property PostCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode
        {
            get
            {
                return this._PostCode;
            }
            set
            {
                this.OnPostCodeChanging(value);
                this.ReportPropertyChanging("PostCode");
                this._PostCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PostCode");
                this.OnPostCodeChanged();
            }
        }
        private string _PostCode;
        partial void OnPostCodeChanging(string value);
        partial void OnPostCodeChanged();
        /// <summary>
        /// There are no comments for Property MSN in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string MSN
        {
            get
            {
                return this._MSN;
            }
            set
            {
                this.OnMSNChanging(value);
                this.ReportPropertyChanging("MSN");
                this._MSN = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("MSN");
                this.OnMSNChanged();
            }
        }
        private string _MSN;
        partial void OnMSNChanging(string value);
        partial void OnMSNChanged();
        /// <summary>
        /// There are no comments for Property Country in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this.OnCountryChanging(value);
                this.ReportPropertyChanging("Country");
                this._Country = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Country");
                this.OnCountryChanged();
            }
        }
        private string _Country;
        partial void OnCountryChanging(string value);
        partial void OnCountryChanged();
        /// <summary>
        /// There are no comments for Property QQ in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string QQ
        {
            get
            {
                return this._QQ;
            }
            set
            {
                this.OnQQChanging(value);
                this.ReportPropertyChanging("QQ");
                this._QQ = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("QQ");
                this.OnQQChanged();
            }
        }
        private string _QQ;
        partial void OnQQChanging(string value);
        partial void OnQQChanged();
        /// <summary>
        /// There are no comments for Music in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("BlueSkyModel", "FK_Music_UserInformation_Id", "Music")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Music> Music
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Music>("BlueSkyModel.FK_Music_UserInformation_Id", "Music");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Music>("BlueSkyModel.FK_Music_UserInformation_Id", "Music", value);
                }
            }
        }
    }
}
